"""
collab.py

(+ conversation so far储存前n-1轮)

This file implements a multi-agent dialogue simulation in which three LLM-based
agents role-play famous fictional detectives (Sherlock Holmes, Miss Marple,
and Hercule Poirot). The agents collaborate purely through natural language
dialogue to solve a murder case.

The purpose of this script is:
1. To generate structured, reproducible multi-agent conversations.
2. To log both dialogue outputs and full prompts for later linguistic analysis.
3. To support research on character consistency (OOC: out-of-character behavior)
   and its impact on collaborative task performance.

"""



# -------------------------------------------------
# Standard library imports
# -------------------------------------------------
import os
import random
import time
import yaml
import csv
import datetime   # with time stamp

# -------------------------------------------------
# Third-party utilities
# -------------------------------------------------
from colorama import Fore, Style, init 


# -------------------------------------------------
# Agent constructors (each wraps an LLM)
# -------------------------------------------------
from agents.holmes_agent import create_agent as create_holmes
from agents.marple_agent import create_agent as create_marple
from agents.poirot_agent import create_agent as create_poirot

# Initialize colored terminal output
init(autoreset=True)


# =================================================
# Utility Functions
# =================================================

def extract_believed_murderer(response: str) -> str:
    """
    Extract the murderer name from an agent's response.

    This function looks for a strict linguistic pattern:
        "I believe the murderer is XXX"

    Rationale (research-oriented):
    -------------------------------
    By forcing all agents to express their hypothesis using an identical surface
    form, we enable:
    - Automatic extraction without semantic parsing
    - Consistent comparison across agents and turns
    - Clean quantitative analysis of agreement / disagreement

    Parameters
    ----------
    response : str
        The full text response generated by an agent.

    Returns
    -------
    str
        The extracted murderer name if present, otherwise an empty string.
    """
    text = response.strip()
    key = "i believe the murderer is "
    idx = text.lower().find(key)
    if idx != -1:
        name = text[idx + len(key):].split()[0]
        return name.strip("：:,.!? ")
    return ""


def clean_response(speaker: str, response: str) -> str:
    """
    Clean the raw LLM output so that it contains only the current agent's utterance.

    This function performs two main sanitization steps:
    1. Removes redundant speaker prefixes (e.g., "Holmes: Holmes: ...")
    2. Truncates the response if the model starts generating other agents' lines

    Rationale:
    ----------
    LLMs sometimes simulate multi-speaker dialogue even when instructed not to.
    This function enforces a strict one-speaker-per-turn protocol, which is
    critical for clean dialogue logs and turn-based analysis.

    Parameters
    ----------
    speaker : str
        The current agent's name ("Holmes", "Marple", or "Poirot").
    response : str
        The raw text returned by the LLM.

    Returns
    -------
    str
        A cleaned version of the response containing only the current speaker's text.
    """
    text = response.strip()

    # remove repeated speaker prefix at the start
    lowers = text.lower()
    while lowers.startswith(speaker.lower() + ":"):
        text = text[len(speaker) + 1:].strip()
        lowers = text.lower()

    # truncate if response contains another agent's name
    for other in ["Holmes", "Marple", "Poirot"]:
        if other != speaker:
            idx = text.find(other + ":")
            if idx != -1:
                text = text[:idx].strip()
    return text


# =================================================
# Core Simulation Class
# =================================================

class DetectiveDialogue:
    """
    Main controller class for the multi-agent detective collaboration.

    Responsibilities:
    -----------------
    - Load experimental rules, case data, and agent prompts
    - Maintain shared dialogue memory
    - Construct prompts for each agent
    - Run the turn-based simulation
    - Log all prompts and dialogue outputs for later analysis

    This class intentionally separates:
    - Prompt construction
    - Dialogue memory
    - Simulation control
    to support transparency and reproducibility in research.
    """

    def __init__(self, rule_path="prompts/rule_collab.yaml", 
                 case_path="cases/case1.yaml", 
                 turns=10):
        """
        Initialize a single experimental run.

        Parameters
        ----------
        rule_path : str
            Path to shared collaboration rules.
        case_path : str
            Path to the murder case description.
        turns : int
            Maximum number of dialogue rounds.
        """
        self.turns = turns
        
        # Shared conversation memory:
        # list of (speaker, utterance) tuples
        self.memory = []  # [(speaker, content)]

        # load global collaboration rules
        with open(rule_path, "r", encoding="utf-8") as f:
            self.rules = yaml.safe_load(f)

        # load full case information
        with open(case_path, "r", encoding="utf-8") as f:
            self.case = yaml.safe_load(f)["case"]

        # initialise agents
        self.agents = {
            "Holmes": create_holmes(),
            "Marple": create_marple(),
            "Poirot": create_poirot(),
        }

        # load agent-specific prompt templates
        self.agent_prompts = {}
        for name in ["holmes", "marple", "poirot"]:
            path = f"prompts/{name}.yaml"
            with open(path, "r", encoding="utf-8") as f:
                self.agent_prompts[name] = yaml.safe_load(f)

        # make sure data dir exists
        os.makedirs("data", exist_ok=True)

        # create run folder with timestamp
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.run_dir = os.path.join("data/case1", f"run_{timestamp}")
        os.makedirs(self.run_dir, exist_ok=True)

        # dialogue log (csv)
        self.dialogue_log_path = os.path.join(self.run_dir, "dialogue_log.csv")
        with open(self.dialogue_log_path, "w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["turn", "speaker", "utterance", "believed_murderer"])

        # prompt log (per agent)
        self.prompt_log_paths = {}
        for agent_name in self.agents.keys():
            path = os.path.join(self.run_dir, f"prompt_log_{agent_name}.txt")
            self.prompt_log_paths[agent_name] = path
            with open(path, "w", encoding="utf-8") as f:
                f.write(f"=== PROMPT LOG for {agent_name} ===\n\n")

    # -------------------------------
    # helper methods
    # -------------------------------
    def update_memory(self, speaker, content):
        """
        Append a single utterance to shared dialogue memory.

        Only surface-level dialogue is stored here.
        System prompts and internal reasoning are intentionally excluded.
        """
        self.memory.append((speaker, content))

    def get_conversation_history_text(self, max_turns=None):
        """
        Convert stored dialogue memory into a formatted text block.
        
        Return all turns if max_turns is None.
        Otherwise return the last max_turns turns.
        """
        if max_turns is None:
            source = self.memory
        else:
            source = self.memory[-max_turns:]
        history = [f"{speaker}: {content}" for speaker, content in source]
        return "\n".join(history)

    def get_partial_clues(self, agent_name):
        """
        Provide each agent with only a subset of the case information.

        Rationale:
        ----------
        This enforces information asymmetry, encouraging genuine collaboration
        and knowledge integration through dialogue.

        Returns
        -------
        dict
            A dictionary containing partial clues relevant to the agent.
        """
        if agent_name == "Holmes":
            return {
                "crime_scene": self.case.get("crime_scene", {}),
                "forensic_evidence": self.case.get("forensic_evidence", {}),
            }
        elif agent_name == "Marple":
            return {
                "suspects": self.case.get("suspects", []),
            }
        elif agent_name == "Poirot":
            return {
                "timeline": self.case.get("timeline", []),
            }
        else:
            return {}

    def build_system_prompt(self, agent_name, agent_prompt):
        """
        Construct the system prompt for a single agent.

        This prompt includes:
        - Global collaboration rules
        - Agent-specific role-play constraints
        - Protective instructions to prevent OOC behavior
        - A task description with partial case clues

        Note:
        -----
        This prompt is NOT stored in dialogue memory.
        """
        role_play = "\n".join(
            [f"- {r['description']}" for r in agent_prompt.get("role_play", [])]
        )
        protective = "\n".join(
            [f"- {p['description']}" for p in agent_prompt.get("protective", [])]
        )

        # partial clues
        partial_clues = self.get_partial_clues(agent_name)
        task_template = agent_prompt.get("task", "")
        task_text = task_template.format(**partial_clues)

        system_prompt = f"""
    
    === Background ===
    {self.rules.get('common_intro', '').format(agent_name=agent_name)}

    === Collaboration Rules ===
    {self.rules.get('common_rules', '')}

    === Role Play Guidelines ===
    {role_play}

    === Protective Guidelines ===
    {protective}

    === Task ===
    {task_text}

    IMPORTANT:
    - Begin with self-introductions because you don’t know each other.
    - Share your full exclusive clues.
    - Speak in coherent, self-contained paragraphs with a clear beginning, middle, and end.
    - Keep responses ideally under 5 sentences and never repeat phrases ever.
    - Listen and interact; do not drift into your own world. If the previous speaker identifies a different murderer, clearly express your disagreement and thoughts.
    - Strictly follow Role Play Guidelines and your investigation style, and strictly avoid behaviours in Protective Guidelines.
    - End every reply with exactly this format, naming one and only one suspect: I believe the murderer is XXX
    """
    
        return system_prompt

    def build_prompt_for_agent(self, agent_name, agent_prompt):
        """
        Combine system prompt and full dialogue history into a single prompt.

        This is the exact text sent to the LLM.
        """
        system_prompt = self.build_system_prompt(agent_name, agent_prompt)
        history_text = self.get_conversation_history_text(max_turns=None)  # ✅ full history

        full_prompt = f"""{system_prompt}

=== Conversation So Far ===
{history_text if history_text else "(no conversation yet)"}
        """
        return full_prompt

    def save_prompt_log(self, agent_name, prompt_text, turn):
        """
        Save the full prompt used for an agent at a given turn.

        This enables:
        - Prompt-level reproducibility
        - Post-hoc analysis of prompt drift or leakage
        """
        path = self.prompt_log_paths[agent_name]
        with open(path, "a", encoding="utf-8") as f:
            f.write(f"--- Turn {turn}, Agent: {agent_name} ---\n")
            f.write(prompt_text)
            f.write("\n\n")

    def save_dialogue_log(self, turn, speaker, utterance, believed_murderer=""):
        """
        Save a single dialogue turn to CSV.

        This structured format supports quantitative linguistic analysis.
        """
        with open(self.dialogue_log_path, "a", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([turn, speaker, utterance, believed_murderer])

    # -------------------------------
    # main simulation loop
    # -------------------------------
    def simulate(self):
        """
        Run the full multi-agent dialogue simulation.

        Each turn:
        - Agents speak in random order
        - Each agent receives the full conversation history
        - Beliefs are extracted and logged
        - Simulation stops early if all agents agree
        """
        colors = {"Holmes": Fore.RED, "Marple": Fore.YELLOW, "Poirot": Fore.BLUE}

        for t in range(1, self.turns + 1):
            print(f"{Fore.MAGENTA}===== Turn {t} ====={Style.RESET_ALL}")

            agent_order = list(self.agents.keys())
            random.shuffle(agent_order)

            beliefs = {}  # 记录本轮每个人的推测

            for agent_name in agent_order:
                agent = self.agents[agent_name]
                agent_prompt = self.agent_prompts[agent_name.lower()]

                # build prompt
                prompt_text = self.build_prompt_for_agent(agent_name, agent_prompt)

                # run
                response_raw = agent.run(prompt_text).strip()
                response = clean_response(agent_name, response_raw)

                # extract believed_murderer
                believed = extract_believed_murderer(response)
                beliefs[agent_name] = believed

                # update memory
                self.update_memory(agent_name, response)

                # save logs
                self.save_prompt_log(agent_name, prompt_text, t)
                self.save_dialogue_log(t, agent_name, response, believed)

                # print to terminal with color
                color = colors.get(agent_name, "")
                print(f"{color}{agent_name}: {response}{Style.RESET_ALL}")
                if believed:
                    print(f"{Fore.GREEN}  ↳ Believes murderer is: {believed}{Style.RESET_ALL}")

                time.sleep(2)

            # ✅ 一轮结束后检查三人意见是否一致
            unique_beliefs = set(beliefs.values()) - {""}
            if len(unique_beliefs) == 1 and len(beliefs) == 3:
                murderer = unique_beliefs.pop()
                print(f"{Fore.CYAN}All detectives agree the murderer is {murderer}! Simulation ends at turn {t}.{Style.RESET_ALL}")
                return

# =================================================
# Script Entry Point
# =================================================

# if __name__ == "__main__":
#     sim = DetectiveDialogue()
#     sim.simulate()

if __name__ == "__main__":
    NUM_RUNS = 1   # ← 一次跑 ~ 轮

    for run_id in range(1, NUM_RUNS + 1):
        print(f"\n{'='*20} EXPERIMENT RUN {run_id} / {NUM_RUNS} {'='*20}\n")

        sim = DetectiveDialogue(
            rule_path="prompts/rule_collab.yaml",
            case_path="cases/case1.yaml",
            turns=10
        )
        sim.simulate()

